### PR TITLE
support adding settings-path for settings.xml

### PR DESCRIPTION
**Pull request by khatib-moh**
As we know that the setup-maven-action uses the settings-maven-action https://github.com/marketplace/actions/maven-settings-action , I have checked the settings-action and inside the action.yaml file there is an attribute for path to override the settings.xml file, I would like to request a support for adding the path attribute.

### CODE REVIEW

**Comment by khatib-moh** [comment]
Hello @slawekjaranowski ,
can you check this please?

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
Please also update README

**Comment by khatib-moh** [comment]
> Please also update README

Hello @slawekjaranowski ,
README  file updated

**Review by slawekjaranowski — DISMISSED** [review]
I will upgrade subject of PR to show what is changed

**Review by robot-simplify4u — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
